version: "3.7"
services:
    database:
        platform: linux/amd64
        image: library/mysql:8.0.26
        container_name: db_containser_name

        cap_add:
            - SYS_NICE
        environment:
            MYSQL_USER: db_user_name
            MYSQL_DATABASE: db_name
            MYSQL_PASSWORD: db_user_password
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        command: ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
        volumes:
            - "./database/:/var/project/db"
        ports:
            - "3306:3306"

    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        depends_on:
            - database
        restart: always
        environment:
            SPRING_DATASOURCE_URL: jdbc:mysql://db_containser_name:3306/db_name?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
            SPRING_DATASOURCE_USERNAME: db_user_name
            SPRING_DATASOURCE_PASSWORD: db_user_password
